spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/member
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        # SQL 포매팅 출력
        format_sql: true
        # SQL 실행 시 주석 포함
        use_sql_comments: true
    show_sql: true
  sql:
    init:
      mode: always
